name: Build and Push FCOS Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'fedora-coreos/**'
  pull_request: [ "main" ]
  workflow_dispatch:

jobs:
  build-fcos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build FCOS image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: fcos
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./fedora-coreos/Containerfile
          context: ./fedora-coreos
          oci: true

      - name: Push to Quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/yalzhang
